version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=decompile_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/decompile_db
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen3.6:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

  worker:
    build: ./workers
    volumes:
      - ./workers:/app
      - ./data:/data
    environment:
      - DATABASE_URL=postgresql://user:password@db/decompile_db
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen3.6:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

  mock_server:
    build:
      context: ./sandbox/mock_server
      dockerfile: ../../backend/Dockerfile # Используем тот же образ, что для backend
    ports:
      - "8080:8000"
    volumes:
      - ./sandbox/mock_server:/app
    environment:
      - APP_MODULE=main:app

volumes:
  postgres_data:
